version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: grip_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grip_invest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Codebase/Backend
      dockerfile: Dockerfile
    container_name: grip_backend
    env_file:
      - ./Codebase/Backend/.env
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  frontend:
    build:
      context: ./Codebase/Frontend
      dockerfile: Dockerfile
    container_name: grip_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:


