name: Build Docker Images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Backend Docker Image
      run: |
        cd Codebase/Backend
        docker build -f Dockerfile.simple -t grip-invest-backend .
        
    - name: Save Backend Image
      uses: actions/upload-artifact@v3
      with:
        name: backend-image
        path: Codebase/Backend/

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Frontend Docker Image
      run: |
        cd Codebase/Frontend
        docker build -t grip-invest-frontend .
        
    - name: Save Frontend Image
      uses: actions/upload-artifact@v3
      with:
        name: frontend-image
        path: Codebase/Frontend/

  build-compose:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Docker Compose
      run: |
        echo "version: '3.8'
        services:
          backend:
            build: ./Codebase/Backend
            ports:
              - '4000:4000'
            environment:
              - NODE_ENV=production
              - DATABASE_URL=mysql://root:dev@1234@localhost:3306/grip_invest
              - JWT_SECRET=your-super-secret-jwt-key-here
          
          frontend:
            build: ./Codebase/Frontend
            ports:
              - '3000:3000'
            environment:
              - NODE_ENV=production
              - NEXT_PUBLIC_API_URL=http://localhost:4000" > docker-compose.yml
      
    - name: Upload Docker Compose
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose
        path: docker-compose.yml
